spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5430/star-bank-database
    username: postgres
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  graphql:
    graphiql:
      enabled: true